In [17]:
import numpy as np 
import sympy as sp
import jacobian as j
import config as c

# Normal Cycle

In [18]:
variables, matrix = j.create_matrix(0,0)

edose before: 40
edose after: 0


In [19]:
matrix

Matrix([
[-RP_LH*(0.6292*(1 + 656100000000*(0.0266666666666667*DomF + 0.01*GrF + 0.0556666666666667*Lut_4 + 1)**8/(656100000000*(0.0266666666666667*DomF + 0.01*GrF + 0.0556666666666667*Lut_4 + 1)**8 + 1001129150390625))*(0.075*Lut_3 + 0.065*Lut_4 + 0.4) + 2.42)/(0.0032*DomF + 0.0012*GrF + 0.00668*Lut_4 + 1.12) + (500 + 2952450000000000*(0.0266666666666667*DomF + 0.01*GrF + 0.0556666666666667*Lut_4 + 1)**8/(656100000000*(0.0266666666666667*DomF + 0.01*GrF + 0.0556666666666667*Lut_4 + 1)**8 + 879638824462890625))/(0.0819672131147541*(1 + 656100000000*(0.0266666666666667*DomF + 0.01*GrF + 0.0556666666666667*Lut_4 + 1)**8/(656100000000*(0.0266666666666667*DomF + 0.01*GrF + 0.0556666666666667*Lut_4 + 1)**8 + 1001129150390625))*(0.075*Lut_3 + 0.065*Lut_4 + 0.4) + 1)],
[                                                                                                                                                                                                                                  

In [20]:
jacobian = matrix.jacobian(variables)

In [30]:
jacobian

Matrix([
[-(0.6292*(1 + 576480100000000*(0.0114285714285714*DomF + 0.00428571428571429*GrF + 0.0238571428571429*Lut_4 + 1)**8/(576480100000000*(0.0114285714285714*DomF + 0.00428571428571429*GrF + 0.0238571428571429*Lut_4 + 1)**8 + 1001129150390625))*(0.075*Lut_3 + 0.065*Lut_4 + 0.7) + 2.42)/(0.0032*DomF + 0.0012*GrF + 0.00668*Lut_4 + 1.28),                                    0,                                                                                                                                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                 

In [21]:
RP_LH, LH, RP_FSH, FSH, RcF, GrF, DomF, Sc_1, Sc_2, Lut_1, Lut_2, Lut_3, Lut_4 = variables


subs = {
    RP_LH:29.65,
    LH:6.86,
    RP_FSH: 8.47,
    FSH:6.15,
    RcF:3.83,
    GrF:11.51,
    DomF:5.48,
    Sc_1:19.27,
    Sc_2: 45.64,
    Lut_1: 100.73,
    Lut_2: 125.95,
    Lut_3: 135.84,
    Lut_4: 168.71
}

evaled_jacobian = jacobian.evalf(subs=subs)

evaled_jacobian

Matrix([
[-12.9672203797344,                  0,                 0,                    0,                  0,     0.261763673373168,     0.698036462328447,    0,     0,     0,                  0,    -4.19783225848543,    -2.18097017557674],
[ 5.18688815189374,              -14.0,                 0,                    0,                  0,   -0.0809971787281965,    -0.215992476608524,    0,     0,     0,                  0,     0.49129900303461,  -0.0250918256236327],
[                0,                  0, -5.32767223313845,                    0,                  0,    0.0842606731230224,     0.138898406864018,    0,     0,     0, -0.276456102495244,   -0.328309153581688,    0.333230797818366],
[                0,                  0,  2.13106889325538,                -8.21,                  0,   -0.0337042692492089,   -0.0898780513312238,    0,     0,     0,                  0,   0.0626862842614424,   -0.133292319127346],
[                0, -0.141350009161785,                 0, 0.00

In [22]:
np_jacobian = np.array(evaled_jacobian.tolist()).astype(np.float64)

In [23]:
import numpy as np
eig_val, eig_vec = np.linalg.eig(np_jacobian)

eig_val

array([-13.92744807+0.j        , -13.04124399+0.j        ,
        -8.21000014+0.j        ,  -5.32767201+0.j        ,
        -1.09714312+0.j        ,  -0.98100483+0.27365481j,
        -0.98100483-0.27365481j,  -0.61544518+0.39803635j,
        -0.61544518-0.39803635j,  -0.13566873+0.j        ,
        -0.25685021+0.21622567j,  -0.25685021-0.21622567j,
        -0.40446586+0.j        ])

# Low Dose Both

In [24]:
p_dose, e_dose = c.dosing_dict['Low Both']
variables, matrix = j.create_matrix(e_dose,p_dose)

edose before: 0
edose after: 40


In [25]:
jacobian = matrix.jacobian(variables)

In [26]:
RP_LH, LH, RP_FSH, FSH, RcF, GrF, DomF, Sc_1, Sc_2, Lut_1, Lut_2, Lut_3, Lut_4 = variables


subs = {
    RP_LH:29.65,
    LH:6.86,
    RP_FSH: 8.47,
    FSH:6.15,
    RcF:3.83,
    GrF:11.51,
    DomF:5.48,
    Sc_1:19.27,
    Sc_2: 45.64,
    Lut_1: 100.73,
    Lut_2: 125.95,
    Lut_3: 135.84,
    Lut_4: 168.71
}

evaled_jacobian = jacobian.evalf(subs=subs)

evaled_jacobian

Matrix([
[-12.2711869563966,                  0,                 0,                    0,                  0,     0.199543547815613,     0.532116127508305,    0,     0,     0,                  0,    -4.06670106552323,     -2.41368184061321],
[ 4.90847478255863,              -14.0,                 0,                    0,                  0,   -0.0716226174453417,    -0.190993646520911,    0,     0,     0,                  0,    0.459061910457799, -0.000845581382310195],
[                0,                  0, -4.27162497860241,                    0,                  0,    0.0601123708148307,     0.074502934042174,    0,     0,     0, -0.276456102495244,   -0.295523497683266,     0.227219483414731],
[                0,                  0,  1.70864999144096,                -8.21,                  0,   -0.0240449483259323,    -0.064119862202486,    0,     0,     0,                  0,   0.0495720219020735,   -0.0908877933658926],
[                0, -0.141350009161785,                 0, 

In [27]:
np_jacobian = np.array(evaled_jacobian.tolist()).astype(np.float64)

In [28]:
eig_val2, eig_vec2 = np.linalg.eig(np_jacobian)

eig_val2

array([-13.96861929+0.j        , -12.30322797+0.j        ,
        -8.21000007+0.j        ,  -4.27162483+0.j        ,
        -1.10350818+0.j        ,  -0.98210655+0.27881973j,
        -0.98210655-0.27881973j,  -0.6135523 +0.40076408j,
        -0.6135523 -0.40076408j,  -0.13455916+0.j        ,
        -0.25539938+0.21690586j,  -0.25539938-0.21690586j,
        -0.40451656+0.j        ])

In [29]:
# Normal cycle
eig_val

array([-13.92744807+0.j        , -13.04124399+0.j        ,
        -8.21000014+0.j        ,  -5.32767201+0.j        ,
        -1.09714312+0.j        ,  -0.98100483+0.27365481j,
        -0.98100483-0.27365481j,  -0.61544518+0.39803635j,
        -0.61544518-0.39803635j,  -0.13566873+0.j        ,
        -0.25685021+0.21622567j,  -0.25685021-0.21622567j,
        -0.40446586+0.j        ])